In [1]:
import numpy as np

In [2]:
a = [i for i in range(10)]

In [3]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
b = np.array(a)

In [5]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
              [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [7]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [8]:
b.shape

(3, 10)

## Операции с векторами

In [9]:
a = np.random.randint(1, 10, 5)
a

array([8, 5, 1, 5, 6])

In [10]:
b = np.random.randint(1, 10, 5)
b

array([1, 8, 3, 4, 7])

In [11]:
print(a.size, b.size, a.shape, b.shape)

5 5 (5,) (5,)


###  При сложении, вычитании и скалярном произведении векторов их размерность должна совпадать

#### Сложение векторов

In [12]:
c = np.add(a, b)
c

array([ 9, 13,  4,  9, 13])

#### Вычитание векторов

In [13]:
a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)
print(a, b, sep = "\n")

[8 3 8 1 9]
[9 6 7 9 1]


In [14]:
d = np.subtract(a, b)
d

array([-1, -3,  1, -8,  8])

#### Умножение векторов

In [15]:
a = np.random.randint(1, 10, 5)
a

array([6, 1, 8, 1, 1])

In [16]:
c = a * 2
c

array([12,  2, 16,  2,  2])

In [17]:
c = a * -10
c

array([-60, -10, -80, -10, -10])

In [18]:
c = a.dot(-10)
c

array([-60, -10, -80, -10, -10])

In [19]:
np.dot(-10, a)


array([-60, -10, -80, -10, -10])

In [20]:
np.multiply(-10, a)

array([-60, -10, -80, -10, -10])

In [21]:
c = a * 0.5
c

array([3. , 0.5, 4. , 0.5, 0.5])

#### Скалярное произведение векторов

In [22]:
a = np.random.randint(1, 10, 3)
b = np.random.randint(1, 10, 3)
print(a, a.shape, b, b.shape, sep = "\n")

[5 8 9]
(3,)
[7 8 8]
(3,)


In [23]:
sp = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
sp

171

In [24]:
a@b

171

In [25]:
sp = np.dot(a, b)
sp

171

#### Операции с матрицами 

In [30]:
a = np.random.randint(1, 10, size=(3,2))
b = np.random.randint(1, 10, size=(3,2))
print(a, a.shape, "", b, b.shape, sep = "\n")

[[4 4]
 [9 7]
 [8 7]]
(3, 2)

[[7 2]
 [9 2]
 [7 2]]
(3, 2)


#### Сложение матриц

In [32]:
c = np.add(a,b)
c

array([[11,  6],
       [18,  9],
       [15,  9]])

#### Вычетание матриц

In [34]:
d = np.subtract(a,b)
d

array([[-3,  2],
       [ 0,  5],
       [ 1,  5]])

#### Умножение матрицы на скаляр

In [38]:
x = np.random.randint(1, 10, size=(2,2))
print(x, x.shape, sep='\n')

[[2 1]
 [3 5]]
(2, 2)


In [39]:
y = np.dot(x, 3)
y

array([[ 6,  3],
       [ 9, 15]])

#### Умножение матриц

In [42]:
X1 = np.random.randint(1, 20, size=(3,2))
X2 = np.random.randint(1, 20, size=(2,4))
print(X1, X2, X1.shape[1] == X2.shape[0]Найдите скалярное произведение столбцов массива, sep='\n')

[[ 2  1]
 [14 19]
 [ 9  9]]
[[11 12 13  3]
 [18 19 10 10]]
True


In [43]:
Z = np.dot(X1, X2)
Z

array([[ 40,  43,  36,  16],
       [496, 529, 372, 232],
       [261, 279, 207, 117]])

#### 
Как получен элемент матрицы Z нулевой строки и нулевого столбца:

In [45]:
Z[0, 0]

40

In [46]:
X1[0, 0] * X2[0, 0] + X1[0, 1] * X2[1, 0]

40

#### 
Как получен элемент матрицы Z нулевой строки и первого столбц:

In [48]:
Z[0, 1]

43

In [49]:
X1[0, 0] * X2[0, 1] + X1[0, 1] * X2[1, 1]

43

### Модуль numpy.linalg: возведение матрицы в квадрат

In [52]:
A = np.random.randint(1, 10, size=(3,3))
A

array([[6, 1, 4],
       [2, 1, 4],
       [9, 7, 7]])

In [53]:
A_square = np.linalg.matrix_power(A, 2)
A_square

array([[ 74,  35,  56],
       [ 50,  31,  40],
       [131,  65, 113]])

### Создание единичной матрицы 
Единичная матрица, матрица с единицами по главной диагонали и нулями в остальных ячейках 

In [57]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

#### Умножение матрицы на единичную матрицу 

In [56]:
A = np.random.randint(1, 10, size=(3, 2))
A

array([[3, 5],
       [9, 9],
       [8, 4]])

In [58]:
np.dot(A, I)

array([[3., 5.],
       [9., 9.],
       [8., 4.]])

In [59]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.dot(I, A)

array([[3., 5.],
       [9., 9.],
       [8., 4.]])

#### Транспонирование матрицы

In [62]:
A = np.random.randint(1, 10, size=(3, 2))
A

array([[2, 4],
       [5, 1],
       [2, 8]])

In [63]:
At = A.transpose()
At

array([[2, 5, 2],
       [4, 1, 8]])

In [65]:
At = A.T
At

array([[2, 5, 2],
       [4, 1, 8]])

In [69]:
X = np.random.randint(1, 10, size=(3, 2))
Y = np.random.randint(1, 10, size=(4, 2))
print(X, Y, sep='\n\n')

[[9 8]
 [4 2]
 [7 6]]

[[2 1]
 [9 7]
 [9 5]
 [7 1]]


In [71]:
Yt= Y.T
Yt

array([[2, 9, 9, 7],
       [1, 7, 5, 1]])

In [73]:
np.dot(X, Yt)

array([[ 26, 137, 121,  71],
       [ 10,  50,  46,  30],
       [ 20, 105,  93,  55]])

#### Вычисление определителя и ранг матрицы 

In [93]:
A = np.random.randint(1, 10, size=(3, 3))
A

array([[2, 5, 8],
       [1, 2, 9],
       [8, 9, 6]])

In [90]:
A = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

In [94]:
np.linalg.det(A)

135.99999999999991

In [95]:
np.linalg.matrix_rank(A)

3

In [96]:
B = np.random.randint(1, 10, size=(3, 2))
B

array([[6, 5],
       [2, 1],
       [9, 3]])

In [97]:
np.linalg.matrix_rank(B)

2

In [100]:
#np.linalg.det(B) # метод только для квадратных матриц

#### Вычесление обратной матрицы

In [101]:
A = np.random.randint(1, 10, size=(3, 3))
A

array([[2, 8, 1],
       [8, 2, 9],
       [2, 1, 7]])

In [103]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.01724138,  0.18965517, -0.24137931],
       [ 0.13103448, -0.04137931,  0.03448276],
       [-0.0137931 , -0.04827586,  0.20689655]])

In [106]:
A_inv2 = np.linalg.inv(A_inv)
A_inv2

array([[2., 8., 1.],
       [8., 2., 9.],
       [2., 1., 7.]])

### Автоматическое создание массивов

In [110]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [111]:
a = np.ones((5, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [112]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
np.arange(0,10, 3)

array([0, 3, 6, 9])

In [120]:
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

In [121]:
np.arange(0,10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

#### numpy.linspase - тоже самое, но граница будет включина. 
  Вместо шага указываем нужное число элементов.
 

In [122]:
np.linspace(0, 9.9, 25)

array([0.    , 0.4125, 0.825 , 1.2375, 1.65  , 2.0625, 2.475 , 2.8875,
       3.3   , 3.7125, 4.125 , 4.5375, 4.95  , 5.3625, 5.775 , 6.1875,
       6.6   , 7.0125, 7.425 , 7.8375, 8.25  , 8.6625, 9.075 , 9.4875,
       9.9   ])

#### numpy.logspase - обе границы включены, но это степени 10

In [128]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

### Генерация случайных чисел

#### np.random.sample - случайные числа с равномерным распределением в промежутке от 0 до 1

In [130]:
np.random.sample()

0.1701786238184575

In [131]:
np.random.sample(5)

array([0.28112748, 0.64628903, 0.02843592, 0.96805781, 0.60240113])

In [132]:
np.random.sample((2,3))

array([[0.94032365, 0.15804629, 0.15058954],
       [0.48277026, 0.94463544, 0.74166235]])

#### 
Массив 48х64х3

Например: это случайное изображение с высотой 48, шириной 64, и значением яркости трех цветов для каждого пикселя.
(трехмерный массив)

In [134]:
np.random.sample((48, 64, 3))

array([[[7.83246199e-02, 8.06838012e-01, 6.57341460e-01],
        [5.28244789e-01, 5.26744843e-01, 5.35529239e-01],
        [3.06824446e-01, 5.69287455e-01, 6.46508106e-01],
        ...,
        [4.51391330e-01, 8.66855069e-01, 3.87247437e-01],
        [4.09014269e-01, 6.77815322e-01, 3.34925114e-04],
        [8.86763711e-01, 6.88525166e-01, 7.06598199e-01]],

       [[1.70310715e-01, 7.52636521e-01, 6.01696588e-01],
        [3.11161055e-01, 9.03948561e-01, 1.73122315e-01],
        [9.87032503e-01, 2.10255813e-01, 9.02278787e-01],
        ...,
        [7.29465600e-01, 8.16975051e-01, 2.13121627e-01],
        [6.57418236e-01, 4.68573951e-03, 8.64998985e-01],
        [2.15954459e-02, 2.28559109e-01, 7.75683830e-01]],

       [[7.14457293e-02, 8.15597549e-01, 8.65018612e-01],
        [5.83914561e-01, 7.90952553e-01, 1.24536252e-02],
        [2.17832812e-01, 1.69755500e-01, 8.24102136e-01],
        ...,
        [8.21444739e-02, 8.14915555e-01, 3.19145618e-01],
        [4.87305430e-01, 1.83

#### numpy.random.randn - случайные числа с нормальным распределением 
(среднее значение = 0, среднеквадратичное отклонение =1)

In [135]:
np.random.randn(10)

array([-0.66241093, -2.97685272,  0.39168411,  0.2933459 , -0.6761996 ,
        0.89325687,  1.06282655, -0.51730209,  0.13090278, -0.55541327])

In [136]:
np.random.randn(3, 4)

array([[-0.58965867, -1.44432051, -1.15967951,  0.46873551],
       [ 0.2578096 , -0.75937632, -1.23939186, -1.64784025],
       [ 0.13568997,  0.67876335, -0.75433202, -0.6057912 ]])

#### numpy.random.randint - массив из целых чисел

In [137]:
np.random.randint(0, 100, 10) 

array([29, 40,  0, 24, 45, 98, 32, 27, 79, 19])

In [138]:
np.random.randint(0, 10, (4, 2)) 

array([[7, 0],
       [0, 8],
       [7, 3],
       [7, 5]])

#### numpy.random.choice - случайный выбор элементов из массива 

In [139]:
b = np.random.randint(0, 10, 8)
b

array([5, 4, 5, 1, 4, 2, 8, 1])

In [141]:
np.random.choice(b)

2

In [142]:
np.random.choice(b, 3)

array([5, 8, 1])

In [144]:
np.random.choice(b, np.random.choice(b))

array([1, 2, 8, 8, 8])

#### numpy.random.seed - иницилизация генератора случайных чисел.
Может использовать для последующей воспроизводимости(будет генерироваться те же числа, если установить одинаковый seed)

In [145]:
np.random.seed(42)

In [146]:
np.random.randint(0, 10, 3)

array([6, 3, 7])

### Изменение формы массива

In [149]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [150]:
a.reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [151]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 
Можно указать требуемое число строк, а в место числа столбцов поставить -1

In [153]:
np.reshape(a, (5, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [155]:
np.reshape(a, (-1, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [158]:
a.resize(5, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [159]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Соединение массивов


In [160]:
a = np.zeros((4, 5))
b = np.ones((4, 5))
print(a,'', b, sep='\n')

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 
вертикальное 

In [161]:
v = np.vstack((a, b))
v

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [162]:
a.shape, b.shape, v.shape

((4, 5), (4, 5), (8, 5))

In [163]:
np.concatenate((a, b), axis = 0) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### 
горизонтальное 

In [164]:
h = np.hstack((a, b))
h

array([[0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]])

#### 
в глубину(третье измерение)

In [165]:
d = np.dstack([a, b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]]])